-- Commentary Archive: per-user records and private screenshot storage.
-- Run once in the Supabase SQL editor. Do not put the database password in the app.

create table if not exists public.fragments (
  row_id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  id text not null,
  title text not null default '',
  quote text not null default '',
  note text not null default '',
  relevance text not null default '',
  resonance text not null default '',
  content text not null default '',
  url text not null default '',
  source_label text not null default '',
  category text not null default 'life' check (category in ('life', 'god', 'tech', 'history', 'science')),
  subcategory text not null default 'growth',
  tags jsonb not null default '[]'::jsonb,
  bucket text not null default 'saved',
  curated boolean not null default false,
  read_error boolean not null default false,
  image_path text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, id)
);

create index if not exists fragments_user_updated_idx on public.fragments (user_id, updated_at desc);
create index if not exists fragments_category_idx on public.fragments (user_id, category, subcategory);

alter table public.fragments enable row level security;

drop policy if exists "People can read their own fragments" on public.fragments;
create policy "People can read their own fragments" on public.fragments for select to authenticated using (auth.uid() = user_id);
drop policy if exists "People can add their own fragments" on public.fragments;
create policy "People can add their own fragments" on public.fragments for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "People can update their own fragments" on public.fragments;
create policy "People can update their own fragments" on public.fragments for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "People can delete their own fragments" on public.fragments;
create policy "People can delete their own fragments" on public.fragments for delete to authenticated using (auth.uid() = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('captures', 'captures', false, 8388608, array['image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "People can view their own captures" on storage.objects;
create policy "People can view their own captures" on storage.objects for select to authenticated using (bucket_id = 'captures' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "People can upload their own captures" on storage.objects;
create policy "People can upload their own captures" on storage.objects for insert to authenticated with check (bucket_id = 'captures' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "People can replace their own captures" on storage.objects;
create policy "People can replace their own captures" on storage.objects for update to authenticated using (bucket_id = 'captures' and (storage.foldername(name))[1] = auth.uid()::text) with check (bucket_id = 'captures' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "People can delete their own captures" on storage.objects;
create policy "People can delete their own captures" on storage.objects for delete to authenticated using (bucket_id = 'captures' and (storage.foldername(name))[1] = auth.uid()::text);
